---
driver:
  name: vagrant

transport:
  name: winrm
  elevated: true
  
provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: mwrock/Windows2012R2
    os_type: windows
    shell_type: powershell 
    driver:
      provider: hyperv
      vm_hostname: chef-fu
      network:
        - ["private_network", {bridge: "Guest"}]

suites:
  - name: default
    run_list:
      - recipe[Chef-GroupPolicy-Resource::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
